# Parameters used for text generation
# Make sure `load` is specified somewhere else
{
  # Text gen type: `input-file`, `unconditional` or `interactive`
  "text-gen-type": "input-file",

  # Params for all
  "maximum_tokens": 102,
  "temperature": 0.8,
  "top_p": 0.0,
  "top_k": 0,
  "recompute": false,

  # `unconditional`: samples
  "num-samples": 1,

  # input/output file
  "sample-input-file": "prompt.txt",
  "sample-output-file": "sample_output3.txt",
}
